### ISSUE TITLE
could not find function r2lim

### ISSUE THREAD

**Issue by fcgportal** [BergmannLab/SingleSampleRNAdynamics#1]
Hi there, thanks you to developed such a great tool to analysis RNA dynamics.
When I run my own data using SingleSampleRNAdynamics, the following error popped out "Error in r2lim(c, t) : could not find function "r2lim"".
Any advance? Thanks!

**Comment by mihersch** [comment]
Hi,
Thanks for using this tool and providing feedback. This error may happen if the optimization function tests for k=1 ±10^-9.  I'll try to provide a fix. I think it can happen when your unlabled and labeled intron to exon ratios sum exactly to one. So in the mean time, you could check if this is the case in your data.

**Comment by mihersch** [comment]
I pushed an update. Can you tell me if the problem persists?

**Comment by fcgportal** [comment]
Thank you so much for your reply. r2lim error is gone, but there is another error: 

Error in ifelse(lb < ub*(1-sign(lb)*eps)/(1+sign(ub)*eps),apply(cbind(lpre.frac,llab.frac,init.par,lbm,ubm),1,function(x)moptim(x[1],x[2], x[3],x[4],x[5])))
  argument "no" is missing, with no default

Would you please check? Thanks again!

**Comment by mihersch** [comment]
It's difficult to know what the problem is without access to your data. It could be that your data is not well formatted or does not satisfy the constraints described in the paper. I pushed a version with a more explicit error message. I'd be interested to know if that changes the output.
